// <auto-generated />
using System;
using Gex.NetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gex.NetCore.Migrations
{
    [DbContext(typeof(GexContext))]
    [Migration("20210616010239_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Gex.NetCore.Models.Curso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("CantAlumnos")
                        .HasColumnType("int");

                    b.Property<int?>("CicloLectivo")
                        .HasColumnType("int");

                    b.Property<string>("Comision")
                        .HasColumnType("text");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Examen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<long?>("MateriaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinTardanza")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int?>("NotaPromo")
                        .HasColumnType("int");

                    b.Property<int?>("NotaRegular")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("Gex.NetCore.Models.FailedJobs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Connection")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Queue")
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FailedJobs");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Materia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MateriasCursos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CursoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<long?>("MateriaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("MateriasCursos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MesaExamen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ExamenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<byte?>("MostrarRespuestas")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("ProfesorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfesorId1")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.HasIndex("ProfesorId1");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MesasAlumnos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AlumnoId")
                        .HasColumnType("bigint");

                    b.Property<string>("AlumnoId1")
                        .HasColumnType("varchar(767)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("MesaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId1");

                    b.HasIndex("MesaId");

                    b.ToTable("MesasAlumnos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.PersonalAccessTokens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Abilities")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<long>("TokenableId")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenableType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("PersonalAccessTokens");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Pregunta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ExamenId")
                        .HasColumnType("bigint");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Respuesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<byte?>("Correcto")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("PreguntaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("Gex.NetCore.Models.RespuestasAlumnos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AlumnoId")
                        .HasColumnType("bigint");

                    b.Property<string>("AlumnoId1")
                        .HasColumnType("varchar(767)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long?>("RespuestaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId1");

                    b.HasIndex("RespuestaId");

                    b.ToTable("RespuestasAlumnos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<long?>("Dni")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("RememberToken")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Examen", b =>
                {
                    b.HasOne("Gex.NetCore.Models.Curso", "Curso")
                        .WithMany("Examenes")
                        .HasForeignKey("CursoId");

                    b.HasOne("Gex.NetCore.Models.Materia", "Materia")
                        .WithMany("Examenes")
                        .HasForeignKey("MateriaId");

                    b.Navigation("Curso");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MateriasCursos", b =>
                {
                    b.HasOne("Gex.NetCore.Models.Curso", "Curso")
                        .WithMany("MateriasCursos")
                        .HasForeignKey("CursoId");

                    b.HasOne("Gex.NetCore.Models.Materia", "Materia")
                        .WithMany("MateriasCursos")
                        .HasForeignKey("MateriaId");

                    b.Navigation("Curso");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MesaExamen", b =>
                {
                    b.HasOne("Gex.NetCore.Models.Examen", "Examen")
                        .WithMany("Mesas")
                        .HasForeignKey("ExamenId");

                    b.HasOne("Gex.NetCore.Models.User", "Profesor")
                        .WithMany("Mesas")
                        .HasForeignKey("ProfesorId1");

                    b.Navigation("Examen");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MesasAlumnos", b =>
                {
                    b.HasOne("Gex.NetCore.Models.User", "Alumno")
                        .WithMany("MesasAlumnos")
                        .HasForeignKey("AlumnoId1");

                    b.HasOne("Gex.NetCore.Models.MesaExamen", "Mesa")
                        .WithMany("MesasAlumnos")
                        .HasForeignKey("MesaId");

                    b.Navigation("Alumno");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Pregunta", b =>
                {
                    b.HasOne("Gex.NetCore.Models.Examen", "Examen")
                        .WithMany("Preguntas")
                        .HasForeignKey("ExamenId");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Respuesta", b =>
                {
                    b.HasOne("Gex.NetCore.Models.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Gex.NetCore.Models.RespuestasAlumnos", b =>
                {
                    b.HasOne("Gex.NetCore.Models.User", "Alumno")
                        .WithMany("RespuestasAlumnos")
                        .HasForeignKey("AlumnoId1");

                    b.HasOne("Gex.NetCore.Models.Respuesta", "Respuesta")
                        .WithMany("RespuestasAlumnos")
                        .HasForeignKey("RespuestaId");

                    b.Navigation("Alumno");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Curso", b =>
                {
                    b.Navigation("Examenes");

                    b.Navigation("MateriasCursos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Examen", b =>
                {
                    b.Navigation("Mesas");

                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Materia", b =>
                {
                    b.Navigation("Examenes");

                    b.Navigation("MateriasCursos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.MesaExamen", b =>
                {
                    b.Navigation("MesasAlumnos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Gex.NetCore.Models.Respuesta", b =>
                {
                    b.Navigation("RespuestasAlumnos");
                });

            modelBuilder.Entity("Gex.NetCore.Models.User", b =>
                {
                    b.Navigation("Mesas");

                    b.Navigation("MesasAlumnos");

                    b.Navigation("RespuestasAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
