name: Deploy to Github Pages
env:
  PUBLISH_DIR: Gex.NetCore/ClientApp/dist
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Change Directory Source
          run: cd Gex.NetCore/ClientApp
        - name: Install packages
          run: npm i
        - name: Run Build
          run: npm run build
        - name: GitHub Pages
          if: success()
          uses: crazy-max/ghaction-github-pages@v1.5.1
          with:
            target_branch: gh-pages
            build_dir: ${{ env.PUBLISH_DIR }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
